const RideConstants = {
  RIDES_RECEIVED: "RIDES_RECEIVED",
  CURRENT_USER_INFO: "CURRENT_USER_INFO",
  NEW_WORKOUT: "NEW_WORKOUT",
  UPDATE_USER: "UPDATE_USER",
  LOGGED_OUT: "LOGGED_OUT",
  CURRENT_USER_TOTALS: "CURRENT_USER_TOTALS",
  USER_TOTALS: "USER_TOTALS",
  RECEIVE_USER: "RECEIVE_USER",
  ADD_FOLLOWINGS: "ADD_FOLLOWINGS",
  REMOVE_FOLLOWING: "REMOVE_FOLLOWING",
  UPDATE_DIRECTIONS: "UPDATE_DIRECTIONS",
  REST_CHART: "REST_CHART",
  RECIVE_ELEVATION_DATA: "RECIVE_ELEVATION_DATA",
  ADD_ROUTE: "ADD_ROUTE",
  STORE_MARKERS: "STORE_MARKERS",
  RECIVE_SAVED_ROUTES: "RECIVE_SAVED_ROUTES",
  SHOW_OLD_ROUTE: "SHOW_OLD_ROUTE",
  REMOVE_ROUTE: "REMOVE_ROUTE",
  RECIVE_ALL_USERS: "RECIVE_ALL_USERS"
};

module.exports = RideConstants;
