const RideConstants = {
  RIDES_RECEIVED: "RIDES_RECEIVED",
  NEW_RIDE: "NEW_RIDE",
  ADD_RIDE: "ADD_RIDE",
  RECEIVE_SAVED_RIDES: "RECEIVE_SAVED_RIDES",
  STORE_MARKERS: "STORE_MARKERS",
  SHOW_OLD_RIDE: "SHOW_OLD_RIDE",
  REMOVE_RIDE: "REMOVE_RIDE",
  RECEIVE_ELEVATION_DATA: "RECEIVE_ELEVATION_DATA",
  UPDATE_DIRECTIONS: "UPDATE_DIRECTIONS",
  REST_CHART: "REST_CHART",
};

module.exports = RideConstants;
