const UserConstants = {
  ADD_FOLLOWING: "ADD_FOLLOWING",
  REMOVE_FOLLOWING: "REMOVE_FOLLOWING",
  USER_TOTALS: "USER_TOTALS",
  RECEIVE_ALL_USERS: "RECEIVE_ALL_USERS",
  UPDATE_USER: "UPDATE_USER",
  RECEIVE_FOLLOWINGS: "RECEIVE_FOLLOWINGS"
};

module.exports = UserConstants;
