---
development:
  cloud_name: ddyl8ojhn
  api_key: '696878857874196'
  api_secret: FTWh3WAGCL-W_v-IEIcJdDWZe_8
  enhance_image_tag: true
  static_image_support: false
production:
  cloud_name: ddyl8ojhn
  api_key: '696878857874196'
  api_secret: FTWh3WAGCL-W_v-IEIcJdDWZe_8
  enhance_image_tag: true
  static_image_support: true
test:
  cloud_name: ddyl8ojhn
  api_key: '696878857874196'
  api_secret: FTWh3WAGCL-W_v-IEIcJdDWZe_8
  enhance_image_tag: true
  static_image_support: false
